COMP: Fix build error in itkAnisotropicDiffusionVesselEnhancementImageFilter.h
This commit fixes this build error due to API change in latest ITK version:

31153-SlicerVMTK-git5458f53-g++-64bits-Qt5.15-Release: /.../SlicerVMTK-build/VMTK/vtkVmtk/Segmentation/itkAnisotropicDiffusionVesselEnhancementImageFilter.txx:409:6: error: no matching function for call to ‘itk::AnisotropicDiffusionVesselEnhancementImageFilter<itk::Image<float, 3>, itk::Image<float, 3> >::ResolveTimeStep(std::vector&, std::vector&)’